### PR TITLE
Hello World Example

### PR DESCRIPTION
**Pull request by DavidCorrado**
Basic hello world example.  I broke up the commits to be easily digestible.  LMK if you have any concerns.  I think we can remove gradle being in kotlin later if we want.

### CODE REVIEW

**Review by OscarFD — APPROVED** [review]
Good stuff!

**Review by OscarFD — APPROVED** [review]

**Review by mike-mathieu — APPROVED** [review]

**Review by mike-mathieu — APPROVED** [review]

**Comment by mike-mathieu** [comment]
@DavidCorrado It says it's still blocked for some reason

**Comment by DavidCorrado** [comment]
I think maybe you all need write access.  I sent invites.

**Comment by DavidCorrado** [comment]
@bigmikehoncho

**Pull request merged**
